## Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this module, we will try to cover the basics of NumPy, focussing on arrays and vectorized operations.

## What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.


## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.


## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.


In [4]:
import numpy as np

# create array using numpy
# create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)



[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [41]:
# create a 2D array 

arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
# arr2.reshape(1,4)


array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [ ]:
# 2D Array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [42]:
# Inbuild Methods
np.arange(0,10,2)



array([0, 2, 4, 6, 8])

In [13]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [14]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [43]:
# Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Attributes of Numpy Array

arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions:  2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [20]:
# Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("Addition:", arr1 + arr2 )

print("Substraction:", arr1 - arr2)

print("Multiplication:", arr1 * arr2)

print("Division:", arr1 / arr2)


Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [24]:
# Universal Function
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sin
print(np.sin(arr))

# Natural log
print(np.log(arr))




[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [ ]:
# Array Slicing & Indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)



Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [49]:
# arr[0]
# arr[0][2]
# print(arr[1:])
# print(arr[0:2,2:])
print(arr[1:2,2:])



[[7 8]]


In [50]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [51]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [52]:
# Statistical Concepts Normalization

data = np.array([1,2,3,4,5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)




Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [53]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)




Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [54]:
# Logical Operation
data = np.array([1,2,34,5,6,7,8,9,10])

data>5


array([False, False,  True, False,  True,  True,  True,  True,  True])

In [58]:
data = np.array([1,2,34,5,6,7,8,9,10])

data[(data >= 5) & (data <=8)]



array([5, 6, 7, 8])

In [33]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])